---
    name: test_main_merge
    on:
      push:
        branches: 
          - main
    
    jobs:
      build-test-publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            
          - name: Set up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.x'
        
          - name: Check endpoint
            run: go build -o endpoint -o build/endpoint main.go
        
          - name: Test application
            run: go test ./...